[apis]
tmdb_api_key = ""

[organization.quality]
preferred_quality = "1080p"

[organization.original_titles]
prefer_original_titles = true
include_english_subtitle = true
fallback_to_english_on_error = true
preserve_original_in_metadata = true
