[apis]
tmdb_api_key = ""

[organization.quality]
preferred_quality = "1080p"

[organization.cjk_titles]
prefer_original_titles = false
include_english_subtitle = false
fallback_to_english_on_error = true
preserve_original_in_metadata = true
