name: "🐛 Bug Report"
description: Report a crash, panic, or unexpected behavior
title: "[bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        For incorrect filename parsing, the issue likely belongs in
        [hunch](https://github.com/lijunzh/hunch/issues) since that's
        where filename parsing lives. Run `hunch "filename"` to check.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Run `plex-org scan /path/to/media`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, plex-org version, install method.
      placeholder: |
        - OS: macOS 15.3
        - plex-org: 0.2.0
        - Install: cargo install
    validations:
      required: false
