name: "✨ Feature Request"
description: Suggest a new feature, command, or improvement
title: "[feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature and why it would be useful.
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example usage
      description: |
        Show how the feature would work — example commands, filenames, etc.
      render: bash
    validations:
      required: false
