# Default configuration for Plex Media Organizer
# This file contains the new simplified configuration structure

[apis]
# TMDB API key - get one for free at https://www.themoviedb.org/settings/api
tmdb_api_key = ""

[parsing]
# Technical terms to filter out from titles
[parsing.technical_terms]
# Release groups to filter out
release_groups = [
    "YIFY", "YTS", "3L", "FRDS", "IAMABLE", "KRaLiMaRKo", "HHWEB", "CtrlHD", 
    "PTHOME", "HDChina", "SyncUP", "DSNP", "SWTYBLZ", "ADE", "PHOBOS", 
    "CHD", "Tv21", "GREENOTEA", "OurTV", "QHstudIo", "DON", "D-Z0N3", "WiKi", 
    "NTb", "HDWinG", "ZigZag", "CMCT", "GPTHD", "PTerWEB", "mUHD",
]

# Video/audio codecs and formats to filter out
codecs = [
    "x264", "x265", "H264", "H265", "AVC", "HEVC", "10bit", "8bit", "TrueHD", 
    "7.1", "5.1", "2.0", "DoVi", "DTS", "AC3", "AAC", "FLAC", "DD5.1", "DTS-HD", 
    "MA", "THD", "HDR", "3Audio", "4Audio", "2Audios", "Atmos", "DDP5", "VC", 
    "TrueHD7", "DD+5", "VC-1", "DDP5.1", "6Audios", "2Audio", "bit",
]

# Quality indicators to filter out
quality = [
    "1080p", "720p", "2160p", "4K", "UHD", "HD", "SD",
]

# Source indicators to filter out
sources = [
    "BluRay", "Blu-ray", "Blu ray", "WEB-DL", "HDTV", "DVDRip", "BRRip", 
    "HDRip", "WEBRip", "REMUX", "UHD", "iTunes", "WEB", "WEB-Rip",
]

# File extensions to filter out (only common ones that might appear in titles)
extensions = [
    "mkv", "mp4", "avi", "part", "cd", "disc", "volume", "vol",
]

# TMDB integration settings
[parsing.tmdb]
# Minimum confidence threshold for TMDB enhancement
min_confidence = 0.3
# Whether to prioritize English titles for TMDB search
prioritize_english = true
# Whether to use TMDB for language detection
use_language_detection = true

# Output formatting preferences
[parsing.output]
# Whether to include quality in the final title
include_quality = false
# Whether to include year in the final title
include_year = true
# Format for non-English movies: "original" or "bilingual"
non_english_format = "bilingual"

[organization]
# Whether to create Plex-style directory structure
create_plex_structure = true
# Whether to move files or copy them
move_files = true
# Whether to preserve original filenames
preserve_original_names = false
